Parameters:
  InstanceType:
    Description: WebServer EC2 instance type, has default, allowed values
    Type: String
    Default: t2.micro
    AllowedValues:
      - t1.micro
      - t2.micro
    ConstraintDescription: must be a valid EC2 instance type
  SecurityGroupPort:
    Description: Port number for the security group
    Type: Number
    MinValue: 1150
    MaxValue: 65535
    ConstraintDescription: must be a valid number in the min-max range.

Resources:
  MyEc2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      AvailabilityZone: us-east-1a
      ImageId: ami-1853ac65